export type AttrFieldType = 'text' | 'number' | 'select' | 'date' | 'boolean' | 'textarea'

export interface AttrField {
  key: string
  label: string
  type: AttrFieldType
  options?: string[]
  placeholder?: string
  unit?: string
  section?: string   // new section heading above this field
  wide?: boolean     // span full width
}

// ─────────────────────────────────────────────────────────────────────────────
const DOMAIN_ATTRS: Record<string, AttrField[]> = {

  // ── PHARMACY ───────────────────────────────────────────────────────────────
  pharmacy: [
    { key:'drug_type',      label:'Drug / Form',       type:'select', section:'Drug Information',
      options:['Tablet','Capsule','Syrup','Suspension','Injection','Cream/Ointment','Drops','Powder','Inhaler','Patch','Suppository','Gel','Lotion','Spray','Implant'] },
    { key:'schedule',       label:'Drug Schedule',     type:'select',
      options:['OTC (No Schedule)','Schedule G','Schedule H','Schedule H1','Schedule X','Schedule C','Schedule C1','Narcotic (NDPS)'] },
    { key:'composition',    label:'Composition / Salt',type:'text',   placeholder:'e.g. Paracetamol 500mg', wide:true },
    { key:'manufacturer',   label:'Manufacturer',      type:'text',   placeholder:'e.g. Sun Pharma' },
    { key:'marketed_by',    label:'Marketed By',       type:'text',   placeholder:'e.g. Cipla Ltd' },
    { key:'pack_size',      label:'Pack Size',         type:'text',   placeholder:'e.g. 10 tablets / strip' },
    { key:'strip_size',     label:'Tablets per Strip', type:'number', placeholder:'10' },
    { key:'batch_no',       label:'Batch No',          type:'text',   section:'Batch & Expiry', placeholder:'e.g. BT2024001' },
    { key:'mfg_date',       label:'Mfg. Date',         type:'date' },
    { key:'expiry_date',    label:'Expiry Date',       type:'date' },
    { key:'storage_cond',   label:'Storage Conditions',type:'select',
      options:['Ambient (15–25°C)','Cool & Dry (8–15°C)','Refrigerated (2–8°C)','Frozen (-20°C)','Protect from Light','Protect from Moisture'] },
    { key:'controlled',     label:'Controlled Substance', type:'boolean', section:'Regulatory' },
    { key:'licence_req',    label:'Requires Drug Licence', type:'boolean' },
    { key:'gst_category',   label:'GST Category',      type:'select',
      options:['Exempt','5% (Life saving)','12%','18%'] },
    { key:'reorder_months', label:'Reorder before Expiry', type:'number', unit:'months', placeholder:'3' },
  ],

  // ── JEWELLERY ──────────────────────────────────────────────────────────────
  jewellery: [
    { key:'metal_type',     label:'Metal Type',         type:'select', section:'Metal Details',
      options:['Gold','Silver','Platinum','Palladium','Rose Gold','White Gold','Oxidised Silver','Kundan','Polki','Diamond'] },
    { key:'purity',         label:'Purity / Fineness',  type:'select',
      options:['24K (999)','22K (916)','18K (750)','14K (585)','9K (375)','925 Sterling Silver','999 Fine Silver','950 Platinum','IISGT Certified'] },
    { key:'gross_wt',       label:'Gross Weight',       type:'number', unit:'g',    placeholder:'0.000' },
    { key:'net_wt',         label:'Net Weight (metal)', type:'number', unit:'g',    placeholder:'0.000' },
    { key:'stone_wt',       label:'Stone Weight',       type:'number', unit:'cts',  placeholder:'0.00' },
    { key:'making_type',    label:'Making Charges Type',type:'select', section:'Pricing & Making',
      options:['Per Gram (₹/g)','Flat Amount (₹)','Percentage of Metal Value (%)','Per Piece'] },
    { key:'making_value',   label:'Making Charges Value',type:'number', placeholder:'0' },
    { key:'wastage_pct',    label:'Wastage %',          type:'number', unit:'%',    placeholder:'0' },
    { key:'stone_charges',  label:'Stone Charges',      type:'number', unit:'₹',    placeholder:'0' },
    { key:'stone_type',     label:'Stone Type',         type:'select', section:'Stone Details',
      options:['None','Diamond','Ruby','Emerald','Sapphire','Pearl','Coral','Turquoise','Amethyst','Topaz','Garnet','Opal','CZ (Cubic Zirconia)','Moissanite','Mixed'] },
    { key:'stone_quality',  label:'Stone Quality',      type:'text',   placeholder:'e.g. VVS1, SI2, AAA' },
    { key:'stone_count',    label:'Stone Count',        type:'number', placeholder:'0' },
    { key:'huid',           label:'HUID (Hallmark ID)', type:'text',   section:'Certification', placeholder:'6-char alphanumeric' },
    { key:'bis_cert',       label:'BIS Cert No',        type:'text',   placeholder:'Certificate number' },
    { key:'design_code',    label:'Design Code',        type:'text',   section:'Design', placeholder:'Internal code' },
    { key:'collection',     label:'Collection Name',    type:'text',   placeholder:'e.g. Bridal 2024' },
    { key:'occasion',       label:'Occasion',           type:'select',
      options:['Everyday Wear','Bridal','Festival','Office Wear','Gift','Custom Order'] },
    { key:'gender',         label:'For',                type:'select', options:['Female','Male','Unisex','Kids'] },
    { key:'size',           label:'Size / Ring Size',   type:'text',   placeholder:'e.g. Ring size 16, Bangle 2.6' },
  ],

  // ── RESTAURANT ─────────────────────────────────────────────────────────────
  restaurant: [
    { key:'food_type',      label:'Food Type',         type:'select', section:'Menu Information',
      options:['Pure Veg','Non-Veg','Egg Only','Vegan','Jain','Contains Pork','Contains Beef'] },
    { key:'course',         label:'Course',            type:'select',
      options:['Starter / Appetizer','Soup','Salad','Main Course','Bread / Rice','Biryani / Rice Bowl','Dal / Curry','Dessert / Mithai','Beverage (Hot)','Beverage (Cold)','Mocktail / Juice','Snack','Combo Meal','Thali'] },
    { key:'cuisine',        label:'Cuisine',           type:'select',
      options:['Indian','North Indian','South Indian','Gujarati','Punjabi','Rajasthani','Mughlai','Chinese','Indo-Chinese','Italian','Continental','Mexican','Thai','Japanese','Fast Food','Street Food','Bakery'] },
    { key:'spice_level',    label:'Spice Level',       type:'select',
      options:['No Spice','Mild','Medium','Spicy','Extra Spicy','Chef\'s Choice'] },
    { key:'serving_size',   label:'Serving Size / Portion', type:'text', placeholder:'e.g. 250ml, Full plate, Half' },
    { key:'available_in',   label:'Available For',     type:'select',
      options:['Breakfast','Lunch','Dinner','All Day','Lunch & Dinner'] },
    { key:'parcel_available', label:'Parcel Available',type:'boolean' },
    { key:'calories',       label:'Calories',          type:'number', unit:'kcal', section:'Nutritional Info', placeholder:'0' },
    { key:'protein_g',      label:'Protein',           type:'number', unit:'g',    placeholder:'0' },
    { key:'carbs_g',        label:'Carbohydrates',     type:'number', unit:'g',    placeholder:'0' },
    { key:'fat_g',          label:'Fat',               type:'number', unit:'g',    placeholder:'0' },
    { key:'allergens',      label:'Allergens',         type:'text',   wide:true,   placeholder:'e.g. Nuts, Dairy, Gluten, Shellfish', section:'Allergens & Kitchen' },
    { key:'prep_time_min',  label:'Prep Time',         type:'number', unit:'min',  placeholder:'15' },
    { key:'kot_station',    label:'KOT Station',       type:'select',
      options:['Main Kitchen','Tandoor','Beverage Counter','Cold Kitchen','Bakery','Live Counter'] },
    { key:'recipe_notes',   label:'Recipe / Chef Notes',type:'textarea', wide:true, placeholder:'Cooking notes or special instructions...' },
    { key:'is_seasonal',    label:'Seasonal Item',     type:'boolean' },
    { key:'is_chef_special',label:'Chef\'s Special',   type:'boolean' },
  ],

  // ── RETAIL / KIRANA ────────────────────────────────────────────────────────
  retail: [
    { key:'brand',          label:'Brand',             type:'text',   section:'Product Identity', placeholder:'e.g. Amul, Haldiram' },
    { key:'manufacturer',   label:'Manufacturer',      type:'text',   placeholder:'e.g. Amul Dairy' },
    { key:'country_origin', label:'Country of Origin', type:'text',   placeholder:'India' },
    { key:'pack_size',      label:'Pack / Net Content', type:'text',  placeholder:'e.g. 500g, 1L, 6 pcs' },
    { key:'pack_type',      label:'Pack Type',         type:'select',
      options:['Loose','Packet','Pouch','Bottle','Tin','Can','Box','Carton','Sachet','Jar'] },
    { key:'shelf_life_days',label:'Shelf Life',        type:'number', unit:'days',  section:'Storage & Shelf', placeholder:'365' },
    { key:'storage_cond',   label:'Storage Conditions',type:'select',
      options:['Ambient','Cool & Dry','Refrigerated (2–8°C)','Frozen','Away from Sunlight'] },
    { key:'shelf_location', label:'Shelf / Rack Location',type:'text', placeholder:'e.g. Rack A-3, Shelf 2' },
    { key:'reorder_qty',    label:'Reorder Qty',       type:'number', section:'Order Management', placeholder:'10' },
    { key:'lead_time_days', label:'Supplier Lead Time',type:'number', unit:'days',  placeholder:'3' },
    { key:'min_order_qty',  label:'Min Order Qty (MOQ)',type:'number', placeholder:'1' },
    { key:'fssai_no',       label:'FSSAI Licence No',  type:'text',   section:'Compliance', placeholder:'Required for food items' },
    { key:'is_food_item',   label:'Food Item',         type:'boolean' },
    { key:'is_returnable',  label:'Returnable to Supplier',type:'boolean' },
  ],

  // ── ELECTRONICS ────────────────────────────────────────────────────────────
  electronics: [
    { key:'brand',          label:'Brand',             type:'text',   section:'Product Identity', placeholder:'e.g. Samsung, Apple' },
    { key:'model_no',       label:'Model Number',      type:'text',   placeholder:'e.g. SM-A546E/DS' },
    { key:'variant',        label:'Variant / Config',  type:'text',   placeholder:'e.g. 8GB/256GB Black' },
    { key:'color',          label:'Color',             type:'text',   placeholder:'e.g. Phantom Black' },
    { key:'ean_upc',        label:'EAN / UPC Code',    type:'text',   placeholder:'13-digit barcode' },
    { key:'category',       label:'Product Category',  type:'select', section:'Specifications',
      options:['Mobile Phone','Tablet','Laptop','Desktop / PC','Smart TV','Audio (Headphones/Speaker)','Wearable (Smartwatch/Band)','Camera','Printer','Projector','Power Bank','Charger/Adapter','Cable/Accessory','Networking','Smart Home','Home Appliance (Large)','Home Appliance (Small)','Gaming','Component / Part','Other'] },
    { key:'voltage',        label:'Voltage',           type:'text',   placeholder:'e.g. 100–240V AC' },
    { key:'wattage',        label:'Wattage / Power',   type:'text',   placeholder:'e.g. 65W' },
    { key:'weight_kg',      label:'Weight',            type:'number', unit:'kg',   placeholder:'0.00' },
    { key:'dimensions',     label:'Dimensions (LxWxH)',type:'text',   placeholder:'e.g. 160x75x8 mm' },
    { key:'warranty_months',label:'Warranty Period',   type:'number', unit:'months', section:'Warranty', placeholder:'12' },
    { key:'warranty_type',  label:'Warranty Type',     type:'select',
      options:['Manufacturer Warranty','Dealer Warranty','No Warranty','Extended Warranty'] },
    { key:'service_centre', label:'Service Centre',    type:'text',   placeholder:'Brand service centre name/location' },
    { key:'serial_required',label:'Serial No. Required per unit', type:'boolean', section:'Tracking' },
    { key:'imei_required',  label:'IMEI Tracking (Mobile)',type:'boolean' },
    { key:'is_import',      label:'Imported Product',  type:'boolean' },
    { key:'import_country', label:'Country of Origin', type:'text',   placeholder:'e.g. China, South Korea' },
    { key:'bis_cert',       label:'BIS / CRS Certification No', type:'text', section:'Compliance', placeholder:'Required for electronics' },
  ],

  // ── SALON ──────────────────────────────────────────────────────────────────
  salon: [
    { key:'service_type',   label:'Service Type',      type:'select', section:'Service Details',
      options:['Hair Cut','Hair Color / Highlights','Hair Treatment','Blow Dry / Styling','Keratin / Smoothening','Hair Extension','Rebonding / Relaxing','Pedicure','Manicure','Nail Extension / Art','Facial','Cleanup','Bleach','Threading','Waxing (Full Body)','Waxing (Part)','Eyebrow / Lash','Makeup (Basic)','Makeup (Bridal)','Massage','Body Polishing','Spa Package','Skin Treatment','Laser/IPL','Tan Removal','Combo Package'] },
    { key:'gender',         label:'For',               type:'select',
      options:['Female','Male','Unisex','Kids (under 12)'] },
    { key:'duration_min',   label:'Duration',          type:'number', unit:'min',   placeholder:'30' },
    { key:'product_used',   label:'Product Brand Used',type:'text',   placeholder:'e.g. Loreal, Schwarzkopf, OPI' },
    { key:'skin_type',      label:'Suitable for Skin Type', type:'select', section:'Suitability',
      options:['All Skin Types','Dry','Oily','Combination','Sensitive','Normal','Mature'] },
    { key:'hair_type',      label:'Suitable for Hair Type',type:'select',
      options:['All Hair Types','Straight','Wavy','Curly','Coily','Fine','Thick','Damaged','Color-treated'] },
    { key:'technician_level',label:'Technician Level', type:'select', section:'Staff & Commission',
      options:['Junior','Senior','Expert/Master','Any'] },
    { key:'commission_pct', label:'Staff Commission',  type:'number', unit:'%',     placeholder:'10' },
    { key:'can_book_online',label:'Online Booking',    type:'boolean', section:'Booking' },
    { key:'advance_pct',    label:'Advance %',         type:'number', unit:'%',     placeholder:'0' },
    { key:'home_service',   label:'Home Service Available', type:'boolean' },
    { key:'home_charges',   label:'Home Service Extra Charge', type:'number', unit:'₹', placeholder:'0' },
  ],

  // ── OPTICAL ────────────────────────────────────────────────────────────────
  optical: [
    { key:'product_category', label:'Product Category',type:'select', section:'Product Type',
      options:['Single Vision Lens','Bifocal Lens','Progressive Lens','Reading Glasses','Sunglasses (Non-Rx)','Frame Only','Contact Lens (Daily)','Contact Lens (Monthly)','Contact Lens (Yearly)','Lens Solution','Accessories'] },
    { key:'brand',          label:'Brand',             type:'text',   placeholder:'e.g. Titan, Fastrack, Ray-Ban, Zeiss' },
    { key:'model_name',     label:'Model Name / Code', type:'text',   placeholder:'e.g. RB2140-901' },
    { key:'lens_material',  label:'Lens Material',     type:'select', section:'Lens Specifications',
      options:['CR-39 (Plastic)','Polycarbonate','Trivex','High Index 1.60','High Index 1.67','High Index 1.74','Glass','Photochromic','Polarised'] },
    { key:'lens_index',     label:'Refractive Index',  type:'select',
      options:['1.50','1.56','1.60','1.67','1.74'] },
    { key:'lens_coating',   label:'Coating',           type:'select',
      options:['None','AR (Anti-Reflective)','UV400','Blue Cut / Blue Light Block','Hydrophobic','Anti-Scratch','Mirror','Gradient'] },
    { key:'sph_range',      label:'SPH Power Range',   type:'text',   placeholder:'e.g. -6.00 to +4.00' },
    { key:'cyl_range',      label:'CYL Range',         type:'text',   placeholder:'e.g. -0 to -2.00' },
    { key:'add_range',      label:'ADD Range (Progressive)', type:'text', placeholder:'e.g. +0.75 to +3.50' },
    { key:'frame_material', label:'Frame Material',    type:'select', section:'Frame Specifications',
      options:['Metal','Stainless Steel','Titanium','TR-90 (Nylon)','Acetate','Rimless','Semi-Rimless','Mixed'] },
    { key:'frame_shape',    label:'Frame Shape',       type:'select',
      options:['Round','Square','Rectangle','Oval','Cat Eye','Aviator','Wayfarer','Sports','Browline','Geometric'] },
    { key:'frame_color',    label:'Frame Color',       type:'text',   placeholder:'e.g. Matte Black, Gold' },
    { key:'frame_size',     label:'Frame Size (E-B-T)',type:'text',   placeholder:'e.g. 52-18-140 mm' },
    { key:'gender',         label:'For',               type:'select',
      options:['Unisex','Men','Women','Kids'] },
    { key:'contact_base_curve', label:'Base Curve (Contact Lens)', type:'text', section:'Contact Lens', placeholder:'e.g. 8.6' },
    { key:'contact_dia',    label:'Diameter',          type:'text',   placeholder:'e.g. 14.2 mm' },
    { key:'contact_water',  label:'Water Content',     type:'text',   placeholder:'e.g. 38%' },
  ],

  // ── CLINIC ─────────────────────────────────────────────────────────────────
  clinic: [
    { key:'service_type',   label:'Service Type',      type:'select', section:'Service Details',
      options:['OPD Consultation','Video Consultation','Follow-up Visit','Procedure','Minor Surgery','Dressing / Wound Care','Vaccination / Immunization','Physiotherapy Session','ECG','Spirometry','Blood Pressure Monitoring','Blood Sugar Test (Point of Care)','Injection','IV Therapy/Drip','Dental Consultation','Dental Procedure','Antenatal Visit','Family Planning','Health Check Package','Certificate / Fitness Test','Emergency Consultation','Home Visit'] },
    { key:'specialization', label:'Specialization / Dept', type:'select',
      options:['General Medicine','Paediatrics','Gynaecology & Obstetrics','Orthopaedics','Dermatology','ENT','Ophthalmology','Cardiology','Neurology','Psychiatry','Endocrinology','Pulmonology','Gastroenterology','Nephrology','Urology','Oncology','Dental','Physiotherapy','Dietetics','General Surgery','Laparoscopic Surgery','Plastic Surgery','Ayurveda','Homoeopathy','Other'] },
    { key:'doctor_name',    label:'Consulting Doctor',  type:'text',   placeholder:'e.g. Dr. Sharma' },
    { key:'duration_min',   label:'Appointment Duration',type:'number',unit:'min',   placeholder:'15' },
    { key:'age_group',      label:'Patient Age Group',  type:'select',
      options:['All Ages','Neonatal (0–28 days)','Infant (1m–1yr)','Toddler (1–3yr)','Child (3–12yr)','Adolescent (12–18yr)','Adult (18–60yr)','Geriatric (60+yr)'] },
    { key:'gender',         label:'Gender Applicability',type:'select',
      options:['All','Female Only','Male Only'] },
    { key:'requires_referral', label:'Requires Referral', type:'boolean', section:'Booking & Rules' },
    { key:'advance_booking_req', label:'Advance Booking Required', type:'boolean' },
    { key:'fasting_req',    label:'Fasting Required',   type:'boolean' },
    { key:'pre_instructions',label:'Patient Instructions',type:'textarea', wide:true, placeholder:'Pre-procedure or pre-appointment instructions...' },
    { key:'is_cashless',    label:'Cashless / Insurance Applicable', type:'boolean', section:'Insurance' },
    { key:'panel_insurers', label:'Panel Insurance Companies', type:'text', wide:true, placeholder:'e.g. Star Health, Medi Assist, TPA...' },
  ],

  // ── SWEET ──────────────────────────────────────────────────────────────────
  sweet: [
    { key:'category',       label:'Category',          type:'select', section:'Product Details',
      options:['Barfi / Burfi','Halwa','Ladoo','Peda','Gulab Jamun','Jalebi','Kalakand','Rasgulla / Rasmalai','Sandesh','Kheer / Payasam','Modak','Gujiya / Karanji','Shrikhand','Basundi','Farsan (Savoury)','Chakli / Murukku','Sev / Gathiya','Bhujia / Mixture','Namkeen','Papad','Bakery – Cake','Bakery – Biscuit/Cookie','Bakery – Bread','Chocolate','Dry Fruits Box','Seasonal Special'] },
    { key:'food_type',      label:'Veg / Non-Veg',     type:'select',
      options:['Pure Veg','Eggless Veg','Contains Egg','Non-Veg'] },
    { key:'main_ingredients', label:'Key Ingredients', type:'text',   wide:true, placeholder:'e.g. Milk, Khoya, Sugar, Saffron' },
    { key:'allergens',      label:'Allergens',         type:'text',   wide:true, placeholder:'e.g. Milk, Nuts, Gluten' },
    { key:'shelf_life',     label:'Shelf Life',        type:'text',   section:'Storage', placeholder:'e.g. 3 days, 15 days, 6 months' },
    { key:'storage_temp',   label:'Storage',           type:'select',
      options:['Ambient Room Temperature','Cool & Dry','Refrigerate (2–8°C)','Deep Freeze (-18°C)'] },
    { key:'packaging',      label:'Available Pack Sizes',type:'text', wide:true, placeholder:'e.g. 250g, 500g, 1kg, 5kg box' },
    { key:'occasion',       label:'Best For',          type:'select', section:'Occasion',
      options:['Everyday','Diwali / Dhanteras','Holi','Raksha Bandhan','Navratri','Eid','Christmas','New Year','Birthday / Anniversary','Puja / Prasad','Corporate Gifting','Wedding / Function','Custom Order'] },
    { key:'is_custom_order',label:'Custom Order Available',type:'boolean' },
    { key:'min_order_kg',   label:'Min Order (for custom)',type:'number', unit:'kg', placeholder:'1' },
    { key:'fssai_no',       label:'FSSAI Licence No',  type:'text',   section:'Compliance' },
  ],

  // ── WHOLESALE ──────────────────────────────────────────────────────────────
  wholesale: [
    { key:'brand',          label:'Brand / Make',      type:'text',   section:'Product Identity', placeholder:'Brand name' },
    { key:'manufacturer',   label:'Manufacturer',      type:'text',   placeholder:'Company name' },
    { key:'country_origin', label:'Country of Origin', type:'text',   placeholder:'India' },
    { key:'sku_code',       label:'Supplier SKU / Catalogue Code', type:'text', placeholder:'Supplier part code' },
    { key:'pack_config',    label:'Pack Configuration',type:'text',   placeholder:'e.g. 1 Carton = 24 pcs' },
    { key:'inner_pack',     label:'Inner Pack Qty',    type:'number', placeholder:'e.g. 12' },
    { key:'outer_pack',     label:'Outer Carton Qty',  type:'number', placeholder:'e.g. 144' },
    { key:'moq',            label:'MOQ (Min Order Qty)',type:'number', section:'Ordering Terms', placeholder:'1' },
    { key:'order_multiple', label:'Order Multiple',    type:'number', placeholder:'1' },
    { key:'lead_time_days', label:'Lead Time',         type:'number', unit:'days',  placeholder:'7' },
    { key:'credit_days',    label:'Credit Period',     type:'number', unit:'days',  placeholder:'30' },
    { key:'dealer_price',   label:'Dealer Price',      type:'number', unit:'₹',    section:'Price Tiers', placeholder:'0' },
    { key:'retailer_price', label:'Retailer Price',    type:'number', unit:'₹',    placeholder:'0' },
    { key:'mrp',            label:'MRP',               type:'number', unit:'₹',    placeholder:'0' },
    { key:'scheme',         label:'Current Scheme',    type:'text',   wide:true,   placeholder:'e.g. 10+1 free, 5% extra margin' },
  ],

  // ── ENTERPRISE ─────────────────────────────────────────────────────────────
  enterprise: [
    { key:'part_no',        label:'Part / Item Number',type:'text',   section:'Item Identity', placeholder:'Internal part code' },
    { key:'oem_no',         label:'OEM Part Number',   type:'text',   placeholder:'Manufacturer\'s part no' },
    { key:'manufacturer',   label:'Manufacturer / OEM',type:'text',   placeholder:'Company name' },
    { key:'category',       label:'Category',          type:'text',   placeholder:'e.g. Raw Material, Consumable, Capital Good' },
    { key:'sub_category',   label:'Sub-Category',      type:'text',   placeholder:'e.g. Fasteners, Lubricants' },
    { key:'specs',          label:'Technical Specs',   type:'textarea', wide:true, placeholder:'Detailed technical specifications...', section:'Specifications' },
    { key:'standard',       label:'Standard / Grade',  type:'text',   placeholder:'e.g. IS 1367, DIN 933, ASTM A36' },
    { key:'uom_primary',    label:'Primary UOM',       type:'text',   placeholder:'e.g. pcs, kg, m, litre' },
    { key:'uom_secondary',  label:'Secondary UOM',     type:'text',   placeholder:'e.g. box, carton' },
    { key:'moq',            label:'MOQ',               type:'number', section:'Ordering', placeholder:'1' },
    { key:'order_multiple', label:'Order Multiple',    type:'number', placeholder:'1' },
    { key:'lead_time_days', label:'Lead Time',         type:'number', unit:'days',  placeholder:'14' },
    { key:'safety_stock',   label:'Safety Stock',      type:'number', placeholder:'50' },
    { key:'reorder_point',  label:'Reorder Point',     type:'number', placeholder:'100' },
    { key:'bis_cert',       label:'BIS / ISO Cert',    type:'text',   section:'Compliance' },
    { key:'test_cert_req',  label:'Test Certificate Required', type:'boolean' },
    { key:'critical_item',  label:'Critical / Long Lead Item', type:'boolean' },
  ],

  // ── AUTOMOBILE ─────────────────────────────────────────────────────────────
  automobile: [
    { key:'part_category',  label:'Part Category',     type:'select', section:'Part Information',
      options:['Engine Parts','Transmission & Gearbox','Brakes & Wheel','Suspension & Steering','Electrical & Battery','Body Parts & Glass','AC & Cooling','Fuel System','Exhaust System','Tyres & Tubes','Lubricants & Fluids','Filters','Belts & Chains','Gaskets & Seals','Spare Accessories','Tools & Equipment','Two-Wheeler Parts','Three-Wheeler Parts'] },
    { key:'part_no_oem',    label:'OEM Part Number',   type:'text',   placeholder:'Original part number' },
    { key:'part_no_alt',    label:'Alternate Part No', type:'text',   placeholder:'Cross-reference number' },
    { key:'brand',          label:'Brand',             type:'text',   placeholder:'e.g. Bosch, Denso, Minda' },
    { key:'part_quality',   label:'Part Quality',      type:'select',
      options:['OEM (Original)','OES (OEM Supplier Brand)','Aftermarket – Premium','Aftermarket – Standard','Reconditioned / Rebuilt'] },
    { key:'compatible_make', label:'Compatible Make',  type:'text',   section:'Compatibility', placeholder:'e.g. Maruti, Tata, Hyundai, Hero' },
    { key:'compatible_model',label:'Compatible Model', type:'text',   wide:true, placeholder:'e.g. Swift, Wagon R, Baleno (add multiple)' },
    { key:'year_from',      label:'Year From',         type:'number', placeholder:'2015' },
    { key:'year_to',        label:'Year To',           type:'number', placeholder:'2024' },
    { key:'engine_cc',      label:'Engine CC',         type:'text',   placeholder:'e.g. 1197cc, 998cc' },
    { key:'fuel_type_compat',label:'Fuel Type',        type:'select',
      options:['Petrol','Diesel','CNG','LPG','Electric','Hybrid','All'] },
    { key:'warranty_months',label:'Warranty',          type:'number', unit:'months', section:'Warranty', placeholder:'6' },
    { key:'warranty_km',    label:'Warranty Km Limit', type:'number', unit:'km',     placeholder:'5000' },
    { key:'made_in',        label:'Made In',           type:'text',   section:'Origin', placeholder:'India / China / Japan' },
  ],

  // ── TEXTILE ────────────────────────────────────────────────────────────────
  textile: [
    { key:'fabric_type',    label:'Fabric Type',       type:'select', section:'Fabric Details',
      options:['Cotton (Pure)','Poly-Cotton Blend','Polyester','Silk (Pure)','Art Silk / Viscose','Rayon','Linen','Wool','Acrylic','Georgette','Chiffon','Crepe','Net / Lace','Velvet','Denim','Satin','Tussar Silk','Kanjivaram Silk','Banarasi','Chanderi','Modal','Bamboo','Organic Cotton','Jute','Canvas'] },
    { key:'composition',    label:'Fibre Composition', type:'text',   placeholder:'e.g. 60% Cotton 40% Polyester' },
    { key:'gsm',            label:'GSM (Weight)',       type:'number', unit:'g/m²', placeholder:'200' },
    { key:'thread_count',   label:'Thread Count',      type:'number',              placeholder:'200 (for bedding)' },
    { key:'width_cm',       label:'Fabric Width',      type:'number', unit:'cm',   placeholder:'115' },
    { key:'sell_by',        label:'Sold by',           type:'select',
      options:['Per Meter','Per Yard','Per Piece / Suit','Per Set (Dress material)','Per Saree','Per Kg'] },
    { key:'pattern',        label:'Pattern / Print',   type:'select', section:'Design',
      options:['Plain / Solid','Checks','Stripes','Floral','Geometric','Abstract','Embroidered','Block Print','Digital Print','Banarasi Weave','Zari Work','Batik','Tie & Dye','Ikat','Ajrak','Bandhani'] },
    { key:'color',          label:'Colour',            type:'text',   placeholder:'e.g. Navy Blue, Off White' },
    { key:'season',         label:'Season',            type:'select',
      options:['All Season','Summer','Winter','Monsoon','Festive/Bridal'] },
    { key:'occasion',       label:'Occasion',          type:'select',
      options:['Casual / Daily Wear','Formal / Office','Party Wear','Festive / Ethnic','Bridal / Wedding','Sportswear','Uniform','Industrial / Workwear','Home Furnishing'] },
    { key:'care',           label:'Washing / Care',    type:'select', section:'Care & Certification',
      options:['Machine Wash Cold','Machine Wash Warm','Hand Wash Only','Dry Clean Only','Do Not Wash','Iron on Low','Do Not Iron'] },
    { key:'is_handloom',    label:'Handloom Certified',type:'boolean' },
    { key:'gi_tag',         label:'GI Tagged Product', type:'boolean' },
  ],

  // ── HOTEL ──────────────────────────────────────────────────────────────────
  hotel: [
    { key:'room_type',      label:'Room / Unit Type',  type:'select', section:'Room Details',
      options:['Standard Single','Standard Double','Standard Twin','Deluxe Single','Deluxe Double','Super Deluxe','Suite (Junior)','Suite (Executive)','Suite (Presidential)','Family Room','Dormitory Bed','Dormitory Room','Studio / Service Apartment','Penthouse','Cottage / Villa','Tent / Glamping'] },
    { key:'bed_type',       label:'Bed Type',          type:'select',
      options:['Single Bed','Double Bed','Twin Beds','King Bed','Queen Bed','Bunk Bed','Rollaway available','Sofa Bed'] },
    { key:'floor',          label:'Floor / Block',     type:'text',   placeholder:'e.g. Ground, 3rd Floor, Block A' },
    { key:'room_nos',       label:'Room Numbers',      type:'text',   wide:true, placeholder:'e.g. 101,102,103 or 201–210' },
    { key:'max_occupancy',  label:'Max Occupancy',     type:'number', placeholder:'2' },
    { key:'extra_bed_allowed', label:'Extra Bed Allowed', type:'boolean' },
    { key:'extra_bed_charge',  label:'Extra Bed Charge', type:'number', unit:'₹/night', placeholder:'0' },
    { key:'child_allowed',  label:'Child Policy',      type:'select',
      options:['Children Welcome (no charge)','Child charge applies','No Children'] },
    { key:'rate_type',      label:'Rate Type',         type:'select', section:'Pricing',
      options:['Per Room Per Night','Per Person Per Night','Per Hour','Per Day (Day Use)','Monthly / Long Stay'] },
    { key:'weekend_rate',   label:'Weekend / Peak Rate',type:'number', unit:'₹',  placeholder:'0' },
    { key:'amenities',      label:'Amenities Included',type:'textarea', wide:true, placeholder:'AC, WiFi, TV, Geyser, Parking, Breakfast...' },
    { key:'view_type',      label:'View',              type:'select',
      options:['Garden View','Pool View','Sea / River View','City View','Mountain View','Courtyard View','No Specific View'] },
    { key:'ac',             label:'Air Conditioned',   type:'boolean', section:'Facilities' },
    { key:'wifi',           label:'WiFi',              type:'boolean' },
    { key:'breakfast_incl', label:'Breakfast Included',type:'boolean' },
    { key:'smoking',        label:'Smoking Room',      type:'boolean' },
    { key:'checkout_time',  label:'Checkout Time',     type:'text',   placeholder:'11:00 AM' },
  ],

  // ── CATERING ───────────────────────────────────────────────────────────────
  catering: [
    { key:'service_type',   label:'Service Type',      type:'select', section:'Service Details',
      options:['Full Event Catering','Lunch / Dinner Service','Breakfast Service','Hi-Tea / Snacks','Cocktail Reception','Live Counter','Tiffin Delivery','Corporate Meals','Wedding / Banquet','Religious / Puja Catering','School / Canteen','Custom Package'] },
    { key:'cuisine',        label:'Cuisine',           type:'select',
      options:['Gujarati','Rajasthani','Punjabi','South Indian','North Indian','Mughlai','Chinese','Continental','Multi-Cuisine','Jain','Satvik / No Onion No Garlic'] },
    { key:'food_type',      label:'Veg / Non-Veg',     type:'select',
      options:['Pure Veg','Non-Veg Available','Mixed (Separate arrangements)'] },
    { key:'service_style',  label:'Service Style',     type:'select',
      options:['Buffet (Self Service)','Seated Plate Service','Thali Service','Parcel / Packed','Live Counter','Mix of above'] },
    { key:'min_pax',        label:'Min. Persons',      type:'number', section:'Capacity & Pricing', placeholder:'50' },
    { key:'max_pax',        label:'Max. Persons',      type:'number', placeholder:'5000' },
    { key:'per_head_rate',  label:'Per Head Rate',     type:'number', unit:'₹',   placeholder:'0' },
    { key:'setup_charges',  label:'Setup / Logistics', type:'number', unit:'₹',   placeholder:'0' },
    { key:'staff_charges',  label:'Service Staff Charges', type:'number', unit:'₹', placeholder:'0' },
    { key:'setup_hrs',      label:'Setup Time Required',type:'number', unit:'hrs',  section:'Operations', placeholder:'3' },
    { key:'service_duration',label:'Service Duration', type:'number', unit:'hrs',  placeholder:'4' },
    { key:'cleanup_incl',   label:'Cleanup Included',  type:'boolean' },
    { key:'utensils_incl',  label:'Utensils / Crockery Included', type:'boolean' },
    { key:'menu_items',     label:'Menu Items Included',type:'textarea', wide:true, placeholder:'List the items covered in this package...' },
    { key:'advance_pct',    label:'Advance Required',  type:'number', unit:'%',    section:'Booking', placeholder:'25' },
    { key:'cancellation',   label:'Cancellation Policy',type:'textarea', wide:true, placeholder:'e.g. 50% refund if cancelled 7 days prior...' },
    { key:'fssai_no',       label:'FSSAI Licence No',  type:'text',   section:'Compliance' },
  ],

  // ── COACHING ───────────────────────────────────────────────────────────────
  coaching: [
    { key:'subject',        label:'Subject',           type:'text',   section:'Course Details', placeholder:'e.g. Mathematics, Physics, English' },
    { key:'board_exam',     label:'Board / Exam Target',type:'select',
      options:['CBSE','ICSE / ISC','Gujarat Board (GSEB)','Maharashtra Board','IIT-JEE (Main)','IIT-JEE (Advanced)','NEET (UG)','NEET (PG)','UPSC / GPSC','Bank Exams (IBPS / SBI)','SSC / Railway','CAT / MBA','GMAT / GRE','IELTS / TOEFL','NATA / Architecture','CA Foundation / Intermediate','Other Competitive','Spoken English / Personality Development','Hobby / Skill (non-exam)'] },
    { key:'grade_level',    label:'Grade / Level',     type:'text',   placeholder:'e.g. Class 10, Class 12, Dropper Batch, Beginner' },
    { key:'mode',           label:'Mode',              type:'select',
      options:['Offline (Classroom)','Online (Live)','Online (Recorded)','Hybrid','Home Tuition','Group Study'] },
    { key:'duration_months',label:'Course Duration',   type:'number', unit:'months', section:'Schedule', placeholder:'12' },
    { key:'hrs_per_month',  label:'Hours per Month',   type:'number', unit:'hrs',    placeholder:'40' },
    { key:'days_per_week',  label:'Days per Week',     type:'number', unit:'days',   placeholder:'5' },
    { key:'batch_timing',   label:'Batch Timing',      type:'select',
      options:['Early Morning (5–7 AM)','Morning (7–9 AM)','Late Morning (9–11 AM)','Afternoon (12–2 PM)','Evening (4–6 PM)','Late Evening (6–8 PM)','Weekend (Sat–Sun)','Flexible / Custom'] },
    { key:'batch_size',     label:'Batch Size (max students)',type:'number', placeholder:'30' },
    { key:'medium',         label:'Teaching Medium',   type:'select', section:'Content',
      options:['English','Hindi','Gujarati','Marathi','English + Hindi','English + Regional'] },
    { key:'study_material', label:'Study Material Included', type:'boolean' },
    { key:'test_series',    label:'Test Series Included', type:'boolean' },
    { key:'doubt_sessions', label:'Doubt Sessions',    type:'select',
      options:['Included (in schedule)','Separate extra class','Online doubt support','Not included'] },
    { key:'fee_structure',  label:'Fee Frequency',     type:'select', section:'Fees',
      options:['Monthly','Quarterly','Half-Yearly','Annual','One-Time (full course)','Per Session'] },
    { key:'emi_available',  label:'EMI / Instalment Option', type:'boolean' },
    { key:'scholarship',    label:'Scholarship Available', type:'boolean' },
    { key:'demo_class',     label:'Free Demo Class',   type:'boolean' },
  ],

  // ── PRINTING ───────────────────────────────────────────────────────────────
  printing: [
    { key:'product_type',   label:'Product Type',      type:'select', section:'Product Details',
      options:['Visiting Card','Letterhead','Envelope','Bill Book / Receipt','Brochure','Pamphlet / Leaflet','Poster','Banner (Flex)','Standee','Catalogue','Calendar','Diary / Notepad','Sticker / Label','Packaging Box','Paper Bag','Wedding Card','Invitation Card','Certificate','ID Card / Badge','Cheque Book','Menu Card','Table Tent','Vinyl Wrap','T-Shirt / Apparel Print','Mug / Gift Print','Other'] },
    { key:'paper_type',     label:'Paper Type',        type:'select',
      options:['Art Paper (Coated)','Art Card','Matte Paper','Offset Paper','Bond Paper','Newsprint','Duplex Board','Kraft Paper','Corrugated Board','Self-Adhesive Vinyl','Polypropylene (PP)','PVC','Canvas','Synthetic Paper'] },
    { key:'paper_size',     label:'Paper Size',        type:'select',
      options:['A1','A2','A3','A4','A5','A6','Letter','Legal','Tabloid','3.5×2" (Visiting Card)','DL Envelope','Custom'] },
    { key:'custom_size',    label:'Custom Size',       type:'text',   placeholder:'Width × Height in mm/inches' },
    { key:'paper_gsm',      label:'Paper GSM',         type:'number', placeholder:'90' },
    { key:'color_mode',     label:'Color Mode',        type:'select', section:'Print Specs',
      options:['Black & White','Full Color (CMYK)','Spot Color (PMS)','Special (Foil/Emboss)'] },
    { key:'sides',          label:'Printing Sides',    type:'select',
      options:['Single Side','Double Side','Both (vary)'] },
    { key:'finish',         label:'Finish / Lamination',type:'select',
      options:['None','Matte Lamination','Gloss Lamination','Soft Touch','UV Spot Coating','Full UV Coating','Aqueous Coating','Embossing','Debossing','Foil Stamping (Gold)','Foil Stamping (Silver)','Die Cutting','Perforation'] },
    { key:'binding',        label:'Binding (for books)',type:'select',
      options:['N/A','Saddle Stitching','Perfect Binding','Spiral Binding','Wiro Binding','Hard Case Binding','Sewn Binding'] },
    { key:'min_qty',        label:'Minimum Quantity',  type:'number', section:'Pricing', placeholder:'100' },
    { key:'rate_per_unit',  label:'Rate per Unit',     type:'number', unit:'₹',  placeholder:'0' },
    { key:'design_charges', label:'Design Charges',    type:'number', unit:'₹',  placeholder:'0' },
    { key:'tat_days',       label:'Turnaround Time',   type:'number', unit:'days', section:'Production', placeholder:'3' },
    { key:'file_format',    label:'Accepted File Formats',type:'text', placeholder:'PDF (print-ready), AI, PSD, INDD' },
    { key:'bleed',          label:'Bleed Requirement', type:'text',   placeholder:'e.g. 3mm bleed on all sides' },
  ],

  // ── LAUNDRY ────────────────────────────────────────────────────────────────
  laundry: [
    { key:'service_type',   label:'Service Type',      type:'select', section:'Service Details',
      options:['Wash & Fold','Wash & Iron','Iron Only','Dry Clean','Steam Press','Stain Removal','Fabric Softener Treatment','Disinfection Wash','Shoe Cleaning','Blanket / Quilt Wash','Curtain Laundry','Carpet Cleaning','Suit / Blazer Dry Clean','Saree Dry Clean','Leather Cleaning','Wedding Dress Cleaning','Alteration / Minor Repair'] },
    { key:'garment_type',   label:'Garment / Item Type',type:'text',  wide:true, placeholder:'e.g. Shirt, Trouser, Saree, Blanket, Suit' },
    { key:'fabric_care',    label:'Special Fabric Care',type:'select',
      options:['Standard','Delicate','Silk / Satin','Woollen','Linen','Embroidered / Beaded','Leather / Suede','Any'] },
    { key:'unit_type',      label:'Charged Per',       type:'select', section:'Pricing',
      options:['Per Piece','Per Kg','Per Set','Per Pair','Per Square Foot','Flat Rate'] },
    { key:'express_hours',  label:'Express TAT',       type:'number', unit:'hrs', section:'Turnaround', placeholder:'6' },
    { key:'standard_days',  label:'Standard TAT',      type:'number', unit:'days', placeholder:'2' },
    { key:'pickup_available',label:'Pickup & Delivery', type:'boolean' },
    { key:'pickup_charges', label:'Pickup Charges',    type:'number', unit:'₹',   placeholder:'0' },
    { key:'subscription',   label:'Monthly Subscription Plan', type:'boolean' },
  ],

  // ── HARDWARE ───────────────────────────────────────────────────────────────
  hardware: [
    { key:'category',       label:'Product Category',  type:'select', section:'Product Details',
      options:['Fasteners (Nuts/Bolts/Screws)','Nails & Rivets','Pipes & Fittings (Metal)','Pipes & Fittings (PVC/CPVC)','Valves & Cocks','Electrical Wiring & Cables','Switchgear & MCB','Switches & Sockets','Lighting & Fixtures','Paint (Interior)','Paint (Exterior)','Primer / Putty','Wood Fittings','Door Fittings & Locks','Glass & Mirrors','Adhesives & Sealants','Abrasives & Grinding','Safety Equipment','Hand Tools','Power Tools','Construction Chemicals','Welding Material','Sanitary Ware','Tiles (Wall)','Tiles (Floor)','Other Building Material'] },
    { key:'brand',          label:'Brand',             type:'text',   placeholder:'e.g. Anchor, Polycab, Asian Paints' },
    { key:'material',       label:'Material',          type:'text',   placeholder:'e.g. Mild Steel, HDPE, Brass, SS 304' },
    { key:'grade_standard', label:'Grade / Standard',  type:'text',   section:'Specifications', placeholder:'e.g. IS 1367, DIN 933, Grade 8.8' },
    { key:'size_spec',      label:'Size / Dimension',  type:'text',   placeholder:'e.g. M8×30mm, 1/2" BSP, 25mm dia' },
    { key:'finish',         label:'Finish / Coating',  type:'select',
      options:['Plain (Uncoated)','Zinc Plated','Hot Dip Galvanized','Powder Coated','Chrome Plated','Black Oxidised','Stainless (Self Finish)','Painted'] },
    { key:'pack_unit',      label:'Unit of Measure',   type:'select', section:'Packaging',
      options:['Each / Piece','Per Kg','Per Meter','Per Foot','Per Litre','Per Bundle','Per Box','Per Bag','Per Roll','Per Sheet'] },
    { key:'pack_qty',       label:'Pack Quantity',     type:'text',   placeholder:'e.g. 100 pcs/bag, 50 kg/bag' },
    { key:'shelf_location', label:'Rack / Bin Location',type:'text',  placeholder:'e.g. Rack C-12' },
    { key:'reorder_qty',    label:'Reorder Quantity',  type:'number', placeholder:'10' },
  ],

  // ── PETROL PUMP ────────────────────────────────────────────────────────────
  petrol_pump: [
    { key:'fuel_type',      label:'Fuel Type',         type:'select', section:'Fuel Details',
      options:['Petrol (Regular)','Petrol (Premium / Speed)','Diesel (Regular)','Diesel (Premium / Power)','CNG','LPG (Auto)','EV Charging (Unit)','Ethanol Blend (E20)'] },
    { key:'tank_no',        label:'Tank Number',       type:'text',   placeholder:'e.g. Tank 1, Tank 2A' },
    { key:'nozzle_nos',     label:'Nozzle Numbers',    type:'text',   placeholder:'e.g. Nozzle 1, 2, 3' },
    { key:'density',        label:'Density (g/ml)',    type:'number', section:'Quality Parameters', placeholder:'0.720' },
    { key:'octane_cetane',  label:'Octane / Cetane Rating', type:'text', placeholder:'e.g. RON 91, CN 51' },
    { key:'sulphur_ppm',    label:'Sulphur Content',   type:'text',   placeholder:'e.g. BS-VI <10 ppm' },
    { key:'dealer_price',   label:'Dealer Price (DP)', type:'number', unit:'₹/L', section:'Pricing', placeholder:'0.00' },
    { key:'retail_price',   label:'Retail Selling Price',type:'number',unit:'₹/L', placeholder:'0.00' },
    { key:'oil_company',    label:'Oil Company / OMC', type:'select', section:'Supply',
      options:['Indian Oil (IOCL)','Bharat Petroleum (BPCL)','Hindustan Petroleum (HPCL)','Reliance','Shell','Essar / Nayara','Others'] },
    { key:'invoice_unit',   label:'Invoicing Unit',    type:'select',
      options:['Per Litre','Per Kg (CNG)','Per Unit (EV)'] },
  ],

  // ── AGRI ───────────────────────────────────────────────────────────────────
  agri: [
    { key:'category',       label:'Category',          type:'select', section:'Product Details',
      options:['Seeds','Fertilizer – Chemical','Fertilizer – Organic / Bio','Pesticide – Insecticide','Pesticide – Herbicide','Pesticide – Fungicide','Pesticide – Rodenticide','Micronutrient / Soil Amendment','Irrigation Equipment','Farm Tools / Hand Tools','Crop Protection Equipment','Animal Feed','Veterinary Product','Mulching / Plastic','Plant Growth Regulator','Other Agri Input'] },
    { key:'brand',          label:'Brand',             type:'text',   placeholder:'e.g. Syngenta, Bayer, IFFCO' },
    { key:'manufacturer',   label:'Manufacturer / Registrant', type:'text', placeholder:'Company name' },
    { key:'crop_target',    label:'Target Crop(s)',    type:'text',   wide:true, placeholder:'e.g. Cotton, Wheat, Rice, Groundnut – all crops' },
    { key:'pest_target',    label:'Target Pest / Disease',type:'text', wide:true, placeholder:'e.g. Aphids, Powdery Mildew, Broad-leaf weeds' },
    { key:'active_ingredient',label:'Active Ingredient',type:'text',  wide:true, section:'Composition', placeholder:'e.g. Chlorpyrifos 50% EC' },
    { key:'formulation',    label:'Formulation Type',  type:'select',
      options:['EC (Emulsifiable Concentrate)','WP (Wettable Powder)','SC (Suspension Concentrate)','SL (Soluble Liquid)','GR (Granules)','DP (Dust Powder)','WG (Water Dispersible Granule)','AL (Liquid)','Seed Treatment','Other'] },
    { key:'pack_size',      label:'Pack Size',         type:'text',   placeholder:'e.g. 500ml, 1L, 50kg bag' },
    { key:'batch_no',       label:'Batch No',          type:'text',   section:'Batch & Expiry' },
    { key:'mfg_date',       label:'Mfg. Date',         type:'date' },
    { key:'expiry_date',    label:'Expiry Date',       type:'date' },
    { key:'season',         label:'Application Season',type:'select', section:'Usage',
      options:['Kharif (Jun–Oct)','Rabi (Nov–Apr)','Zaid (Mar–Jun)','All Season','Pre-Sowing','Post-Harvest'] },
    { key:'dose',           label:'Recommended Dose',  type:'text',   placeholder:'e.g. 2ml / litre of water' },
    { key:'licence_no',     label:'Pesticide Licence No', type:'text', section:'Regulatory' },
    { key:'reg_no',         label:'CIB&RC Reg. No',    type:'text',   placeholder:'CIR/P/12345' },
    { key:'is_restricted',  label:'Restricted Use Pesticide', type:'boolean' },
  ],

  // ── REPAIR ─────────────────────────────────────────────────────────────────
  repair: [
    { key:'device_category',label:'Device / Item Category', type:'select', section:'Service Details',
      options:['Mobile Phone','Tablet','Laptop','Desktop / PC','Smartwatch / Wearable','Smart TV / Monitor','Printer / Scanner','Camera','Gaming Console','Home Appliance (AC)','Home Appliance (Washing Machine)','Home Appliance (Fridge)','Home Appliance (Microwave)','Home Appliance (Other)','Audio Equipment','Two-Wheeler','Electrical Item','Other Electronics','Other Mechanical'] },
    { key:'service_type',   label:'Repair / Service Type', type:'text', wide:true, placeholder:'e.g. Screen Replacement, Battery Replacement, Motherboard Repair' },
    { key:'compatible_brands',label:'Compatible Brands', type:'text', wide:true, placeholder:'e.g. Samsung, Apple, OnePlus, Dell, HP (All brands / specific)' },
    { key:'part_origin',    label:'Part Quality',       type:'select',
      options:['OEM (Original)','OEM Compatible (A+ Grade)','Premium Aftermarket','Standard Aftermarket','Refurbished Part','Used / Pulled Part'] },
    { key:'warranty_days',  label:'Repair Warranty',    type:'number', unit:'days', section:'Warranty', placeholder:'30' },
    { key:'warranty_scope', label:'Warranty Covers',    type:'text',   wide:true,   placeholder:'e.g. Same fault only / All parts used in this repair' },
    { key:'tat_hours',      label:'Estimated TAT',      type:'number', unit:'hrs',  section:'Turnaround', placeholder:'24' },
    { key:'express_tat_hrs',label:'Express TAT',        type:'number', unit:'hrs',  placeholder:'4' },
    { key:'advance_pct',    label:'Advance Required',   type:'number', unit:'%',    placeholder:'50' },
    { key:'pickup_available',label:'Pickup & Delivery', type:'boolean', section:'Logistics' },
    { key:'pickup_charges', label:'Pickup Charge',      type:'number', unit:'₹',    placeholder:'0' },
    { key:'imei_capture',   label:'IMEI / Serial No Required', type:'boolean' },
  ],

  // ── TIFFIN ─────────────────────────────────────────────────────────────────
  tiffin: [
    { key:'meal_type',      label:'Meal Type',         type:'select', section:'Meal Details',
      options:['Breakfast','Lunch','Dinner','Breakfast + Lunch','Lunch + Dinner','Full Day (B+L+D)','Snack Box'] },
    { key:'food_type',      label:'Food Type',         type:'select',
      options:['Pure Veg','Jain (No root veg)','Non-Veg','Egg','Special Diet / Diabetic Friendly'] },
    { key:'cuisine',        label:'Cuisine Style',     type:'select',
      options:['Gujarati','Punjabi','Rajasthani','South Indian','North Indian','Mix Veg','Custom as per order'] },
    { key:'items_count',    label:'Items in Tiffin',   type:'number', placeholder:'5' },
    { key:'menu_description',label:'Menu Description', type:'textarea', wide:true, placeholder:'e.g. Dal, Sabzi, Roti (3), Rice, Salad, Pickle, Buttermilk' },
    { key:'spice_level',    label:'Spice Level',       type:'select',
      options:['No Spice','Mild','Medium','Regular','Custom on request'] },
    { key:'plan_type',      label:'Subscription Plan', type:'select', section:'Subscription',
      options:['Daily (per meal)','Weekly','Monthly (30 days)','Monthly (Fixed weekdays only)','Trial (3 days)'] },
    { key:'day_type',       label:'Available',         type:'select',
      options:['All 7 days','Weekdays only (Mon–Fri)','Weekdays only (Mon–Sat)','Custom'] },
    { key:'pause_allowed',  label:'Pause / Skip Allowed', type:'boolean' },
    { key:'min_subscription_days',label:'Min Subscription', type:'number', unit:'days', placeholder:'7' },
    { key:'delivery_slot',  label:'Delivery Slot',     type:'select', section:'Delivery',
      options:['7–8 AM','8–9 AM','9–10 AM','11 AM–12 PM','12–1 PM','1–2 PM','7–8 PM','8–9 PM','Custom'] },
    { key:'delivery_areas', label:'Delivery Area / Pincode',type:'text', wide:true, placeholder:'e.g. Alkapuri, Vadodara 390007' },
    { key:'container_type', label:'Container Type',    type:'select',
      options:['Stainless Steel (Returnable)','Disposable (Eco-friendly)','Client owns container','Both options'] },
    { key:'container_deposit',label:'Container Deposit',type:'number', unit:'₹', placeholder:'0' },
  ],

  // ── GYM ────────────────────────────────────────────────────────────────────
  gym: [
    { key:'plan_type',      label:'Plan / Membership Type', type:'select', section:'Membership Details',
      options:['Daily Pass','Weekly Pass','Monthly','Quarterly (3 months)','Half-Yearly (6 months)','Annual','Couple Plan','Family Plan','Student Plan','Senior Citizen Plan','Corporate / Group Plan','Personal Training Package','Online Coaching Package'] },
    { key:'duration_months',label:'Plan Duration',     type:'number', unit:'months', placeholder:'1' },
    { key:'access_type',    label:'Access / Facilities', type:'select',
      options:['Full Gym Access','Cardio Only','Weight Training Only','Cardio + Weights','Swimming Pool','Yoga / Zumba / Aerobics','Functional Training','CrossFit','Boxing / MMA','Squash Court','Full Access (All Facilities)','Specific Class Only'] },
    { key:'batch_timing',   label:'Batch Timing',      type:'select',
      options:['Early Morning (5–7 AM)','Morning (7–9 AM)','Morning (9–11 AM)','Afternoon (12–3 PM)','Evening (4–6 PM)','Evening (6–8 PM)','Late Evening (8–10 PM)','Anytime (Open Access)','Specific Slots'] },
    { key:'gender',         label:'For',               type:'select',
      options:['Male','Female','Unisex','Couples'] },
    { key:'pt_sessions',    label:'PT Sessions Included', type:'number', section:'Inclusions', placeholder:'0' },
    { key:'diet_plan',      label:'Diet Plan Included',type:'boolean' },
    { key:'body_assessment',label:'Body Assessment Included', type:'boolean' },
    { key:'locker_incl',    label:'Locker Included',   type:'boolean' },
    { key:'supplement_discount',label:'Supplement Discount', type:'number', unit:'%', placeholder:'0' },
    { key:'freeze_allowed', label:'Membership Freeze Allowed', type:'boolean', section:'Policy' },
    { key:'freeze_max_days',label:'Max Freeze Days',   type:'number', unit:'days', placeholder:'30' },
    { key:'transfer_allowed',label:'Membership Transfer', type:'boolean' },
    { key:'auto_renewal',   label:'Auto Renewal',      type:'boolean' },
  ],

  // ── DIAGNOSTIC LAB ─────────────────────────────────────────────────────────
  diagnostic_lab: [
    { key:'test_code',      label:'Test Code / Short Name', type:'text', section:'Test Details', placeholder:'e.g. CBC, LFT, TSH, HbA1c' },
    { key:'test_category',  label:'Department / Category', type:'select',
      options:['Haematology','Biochemistry','Microbiology & Culture','Serology / Immunology','Hormones / Endocrinology','Molecular Biology / PCR','Histopathology / Biopsy','Cytology','Urine & Body Fluid','Clinical Pathology','Radiology – X-Ray','Radiology – USG','Radiology – CT Scan','Radiology – MRI','Cardiology – ECG','Cardiology – 2D Echo','Pulmonology – PFT','Neurology – EEG','Ophthalmology – Field Test','Other'] },
    { key:'full_name',      label:'Full Test Name',    type:'text',   wide:true, placeholder:'e.g. Complete Blood Count with Differential' },
    { key:'sample_type',    label:'Sample Type',       type:'select', section:'Sample & Collection',
      options:['Venous Blood (EDTA)','Venous Blood (SST / Serum)','Venous Blood (Fluoride)','Venous Blood (Citrate)','Arterial Blood (ABG)','Capillary Blood','Random Urine','24-hr Urine Collection','Mid-stream Urine (MSU)','Sputum','Throat Swab','Nasal Swab','High Vaginal Swab','Stool / Faecal','CSF (Spinal Fluid)','Pleural / Ascitic Fluid','Synovial Fluid','Skin Scraping','Tissue / Biopsy','Semen','Nail / Hair'] },
    { key:'sample_volume',  label:'Sample Volume',     type:'text',   placeholder:'e.g. 3 ml, 10 ml, Midstream' },
    { key:'container',      label:'Collection Container', type:'text', placeholder:'e.g. EDTA (Purple cap), SST (Yellow cap), Urine cup' },
    { key:'fasting_hrs',    label:'Fasting Required',  type:'number', unit:'hrs', placeholder:'0 (or 8, 12)' },
    { key:'special_prep',   label:'Patient Preparation', type:'textarea', wide:true, placeholder:'Any special instructions before collection...' },
    { key:'home_collection',label:'Home Collection Available', type:'boolean' },
    { key:'tat_hrs',        label:'Regular TAT',       type:'number', unit:'hrs',  section:'Reporting', placeholder:'24' },
    { key:'tat_urgent_hrs', label:'Urgent / STAT TAT', type:'number', unit:'hrs',  placeholder:'2' },
    { key:'reference_range',label:'Reference Range',   type:'textarea', wide:true, placeholder:'e.g. Male: 13.5–17.5 g/dL | Female: 12–15.5 g/dL' },
    { key:'critical_values',label:'Critical / Panic Values', type:'text', wide:true, placeholder:'e.g. <7 or >20 g/dL – notify clinician immediately' },
    { key:'method',         label:'Method / Analyser', type:'text',   placeholder:'e.g. Fluorescence Flow Cytometry (Mindray)' },
    { key:'nabl_accredited',label:'NABL Accredited',   type:'boolean', section:'Accreditation' },
    { key:'iso_15189',      label:'ISO 15189 Certified', type:'boolean' },
  ],

  // ── PEST CONTROL ───────────────────────────────────────────────────────────
  pest_control: [
    { key:'service_type',   label:'Service Type',      type:'select', section:'Service Details',
      options:['General Disinfection','Cockroach Control (Gel)','Cockroach Control (Spray)','Rodent Control (Bait)','Rodent Control (Trap)','Bed Bug Treatment','Mosquito Control (Fogging)','Mosquito Control (Larvicide)','Termite Control (Pre-construction)','Termite Control (Post-construction – Drilling)','Termite Baiting System','Ant Control','Fly Control','Wood Borer Treatment','Bee / Wasp Removal','Bird Control / Netting','Snake Removal','Annual Maintenance Contract (AMC)','Herbal / Non-Chemical Treatment'] },
    { key:'pest_target',    label:'Target Pest',       type:'text',   wide:true,   placeholder:'e.g. German Cockroach, Subterranean Termite, Rodents' },
    { key:'area_sqft',      label:'Coverage Area',     type:'number', unit:'sq ft', section:'Coverage', placeholder:'1000' },
    { key:'property_type',  label:'Property Type',     type:'select',
      options:['Residential Flat','Bungalow / Villa','Commercial Office','Restaurant / Hotel','Factory / Warehouse','Hospital','School / College','Retail Shop','Construction Site / Pre-con','Outdoor / Landscape'] },
    { key:'chemical_used',  label:'Chemical / Product', type:'text',  wide:true,   placeholder:'e.g. Bifenthrin 10% EC, Imidacloprid gel' },
    { key:'method',         label:'Application Method',type:'select', section:'Method',
      options:['Gel Application','Residual Spray','Space Spray / Fogging','Baiting','Drilling & Rodding','Heat Treatment','Fumigation','Trapping','Biological Control','Baiting Station'] },
    { key:'sessions',       label:'No. of Sessions',   type:'number', section:'Sessions & Warranty', placeholder:'1' },
    { key:'session_interval',label:'Session Interval', type:'text',   placeholder:'e.g. Every 3 months' },
    { key:'warranty_months',label:'Service Warranty',  type:'number', unit:'months', placeholder:'3' },
    { key:'amc_available',  label:'AMC Available',     type:'boolean' },
    { key:'certificate_issued',label:'Pest Control Certificate Issued', type:'boolean' },
    { key:'licence_no',     label:'Licence / Reg. No', type:'text',   section:'Compliance' },
    { key:'advance_pct',    label:'Advance Required',  type:'number', unit:'%',    placeholder:'50' },
  ],

  // ── PHOTOGRAPHY ────────────────────────────────────────────────────────────
  photography: [
    { key:'service_type',   label:'Service / Package Type', type:'select', section:'Service Details',
      options:['Wedding Photography','Wedding Videography','Wedding Photo + Video','Pre-Wedding Shoot','Engagement Ceremony','Baby Shower / Cradle','Maternity Shoot','New Born Baby Shoot','Birthday Party','Anniversary','Portrait Session','Family Portrait','Corporate / LinkedIn Headshot','Product Photography','Food Photography','Architecture / Interior','Fashion / Model Portfolio','School / College Annual Day','Event Coverage','Graduation Shoot','Drone Photography','360° Virtual Tour','Videography Only','Album / Print Only'] },
    { key:'coverage_hrs',   label:'Coverage Hours',    type:'number', unit:'hrs',  section:'Coverage', placeholder:'8' },
    { key:'no_of_shooters', label:'No. of Photographers/Videographers', type:'number', placeholder:'2' },
    { key:'no_of_cameras',  label:'No. of Camera Setups', type:'number', placeholder:'2' },
    { key:'drone',          label:'Drone Included',    type:'boolean' },
    { key:'photo_count',    label:'Edited Photos Delivered',type:'number', section:'Deliverables', placeholder:'300' },
    { key:'raw_files',      label:'RAW Files Provided',type:'boolean' },
    { key:'video_duration', label:'Final Video (edited)',type:'text',   placeholder:'e.g. 10 min cinematic film, 30 sec reel' },
    { key:'album_incl',     label:'Photo Album Included',type:'boolean' },
    { key:'album_pages',    label:'Album Size',        type:'text',   placeholder:'e.g. 16×20" – 40 pages' },
    { key:'short_film',     label:'Short Film / Highlights Reel', type:'boolean' },
    { key:'delivery_days',  label:'Delivery in',       type:'number', unit:'days', section:'Delivery', placeholder:'30' },
    { key:'delivery_medium',label:'Delivery Medium',   type:'select',
      options:['Google Drive / Cloud Link','USB / Pen Drive','DVD','Online Gallery','Printed Copies','All of the above'] },
    { key:'location',       label:'Location',          type:'select', section:'Logistics',
      options:['Client\'s Location','Studio (Indoor)','Outdoor Location','Destination','Multiple Locations'] },
    { key:'advance_pct',    label:'Advance %',         type:'number', unit:'%',   section:'Booking', placeholder:'25' },
    { key:'cancellation',   label:'Cancellation Policy',type:'textarea', wide:true, placeholder:'e.g. 50% refund if cancelled 15 days prior...' },
  ],
  // ── MILK DAIRY ─────────────────────────────────────────────────────────────
  milk_dairy: [
    { key:'milk_type',      label:'Product Type',       type:'select', section:'Milk Details',
      options:['cow','buffalo','toned','double_toned','skimmed','a2','goat','mixed','curd','paneer','ghee','buttermilk','deposit','other'] },
    { key:'fat_pct',        label:'Fat %',              type:'number', unit:'%',    placeholder:'3.5' },
    { key:'snf_pct',        label:'SNF %',              type:'number', unit:'%',    placeholder:'8.5' },
    { key:'pack_type',      label:'Pack Type',          type:'select',
      options:['loose','pouch','bottle_glass','bottle_plastic','tetra'] },
    { key:'price_per_litre',label:'Price per Litre',    type:'number', unit:'₹',    placeholder:'0' },
    { key:'is_deposit',     label:'Deposit / Refundable', type:'boolean' },
  ],

  // ── IRON & STEEL ───────────────────────────────────────────────────────────
  iron_steel: [
    { key:'shape',           label:'Shape / Profile',    type:'select', section:'Product Specifications',
      options:['TMT Bar','Round Rod','Flat Bar','Square Bar','Sheet (HR)','Sheet (CR)','Plate','Chequered Plate','Pipe (Round)','Pipe (Square/Rect)','Angle','Channel','I-Beam','H-Beam / Column','Wire Rod','Other'] },
    { key:'grade',           label:'Grade / Standard',   type:'text',   placeholder:'e.g. Fe500D, IS2062 E250, IS513 CR2' },
    { key:'diameter_mm',     label:'Diameter / Size',    type:'select', section:'Dimensions',
      options:['6mm','8mm','10mm','12mm','16mm','20mm','25mm','28mm','32mm','40mm','Custom'] },
    { key:'length_ft',       label:'Length',             type:'text',   placeholder:'e.g. 40 ft, 12 m' },
    { key:'thickness_mm',    label:'Thickness (mm)',     type:'number', unit:'mm',  placeholder:'6' },
    { key:'width_mm',        label:'Width (mm)',         type:'number', unit:'mm',  placeholder:'1250' },
    { key:'weight_per_unit_kg', label:'Weight per Piece/Rod', type:'number', unit:'kg', placeholder:'47.1' },
    { key:'finish',          label:'Finish / Treatment', type:'select', section:'Quality',
      options:['Hot Rolled (HR)','Cold Rolled (CR)','Galvanized (GI)','Powder Coated','Epoxy Coated','Polished (No. 4)','Pickled & Oiled'] },
    { key:'mill',            label:'Mill / Brand',       type:'text',   placeholder:'e.g. SAIL, Tata Tiscon, JSW, Jindal' },
    { key:'sold_by',         label:'Billed Per',         type:'select', section:'Pricing',
      options:['Per Kg','Per MT (Metric Tonne)','Per Quintal','Per Piece','Per Bundle','Per Coil'] },
    { key:'is_test_cert_required', label:'MTC Required', type:'boolean' },
    { key:'reorder_qty',     label:'Reorder Level',      type:'number', unit:'MT', section:'Inventory', placeholder:'5' },
  ],
}

export function getDomainAttrs(domainType: string): AttrField[] {
  return DOMAIN_ATTRS[domainType] ?? []
}
